###########################   admin routes   #################

### admin login
POST http://localhost:8080/api/admin/login
Content-Type: application/json

{  
   "email": "admin@gmail.com",
   "password": "9572013"
}

###  admin logout
DELETE http://localhost:8080/api/admin/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU

### admin forgot password
PATCH  http://localhost:8080/api/admin/forgot-password
Content-Type: application/json

{  
   "email": "admin@gmail.com",
   "mobile": "9123456789"
}

### admin change password
PATCH  http://localhost:8080/api/admin/change-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU

{  
   "currentPassword": "82792535",
   "newPassword": "123456"
}



### admin view single editor
GET http://localhost:8080/api/admin/view-single-editor/5ee72bd9c427b635c00cea4d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU


### admin udpate single editor
PATCH  http://localhost:8080/api/admin/update-editor/5ee72bd9c427b635c00cea4d?status=blocked
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU


### admin filter editors
GET http://localhost:8080/api/admin/filter-editors?status=requested
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU


### admin search editors by officeName
GET http://localhost:8080/api/admin/search/editors-by-office-name?officeName=editor1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU










#################### editor routes #######################

### editor register
POST http://localhost:8080/api/editor/register
Content-Type: application/json

{  
   "name": "editor4",
   "email": "editor4@gmail.com",
   "password": "123456",
   "mobile":"9123456789",
   "officeName":"editor4 office",
   "address":"hyderabad"
}

### editor login
POST http://localhost:8080/api/editor/login
Content-Type: application/json

{  
   "email": "editor1@gmail.com",
   "password": "123456"
}

###  editor logout
DELETE http://localhost:8080/api/editor/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU

### editor forgot password
PATCH  http://localhost:8080/api/editor/forgot-password
Content-Type: application/json

{  
   "email": "editor1@gmail.com",
   "mobile": "9123456789"
}

### editor change password
PATCH  http://localhost:8080/api/editor/change-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU

{  
   "currentPassword": "13008956",
   "newPassword": "123456"
}


### editor creating customer account
POST http://localhost:8080/api/editor/create-customer-account
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

{  
   "name": "customer2",
   "email": "customer2@gmail.com",
   "password": "123456",
   "officeName":"customer2",
   "mobile":"9123456789",
   "address":"hyderabad"
}

### editor viewing single customer
GET http://localhost:8080/api/editor/view-single-customer/5ee74eac6f17882db429c490
Content-Type: application/json  
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o


### editor removing customer
DELETE  http://localhost:8080/api/edior/remove-customer/5ee74abfda2b4f29f06bafdb
Content-Type: application/json  
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MTA5MzUyZWRjNDQxN2EzNGQ2ZmYiLCJpYXQiOjE1OTIyMTY0NDMsImV4cCI6MTU5MjMwMjg0M30.oACaeMHlH1LTZ5Rba-5NoD74gybFspG-fzhVKy2_UvU


### editor clciking on create order
GET http://localhost:8080/api/editor/get-customer-ids
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o


### editor creating order
POST http://localhost:8080/api/editor/create-order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

{  
   "customerId": "5ee74eb76f17882db429c491",
   "titleOfOrder": "anniversary in hyd",
   "typeOfOrder": "anniversary",
   "description": "should make a beautiful video editing",
   "outPutFormat":"blu-ray",
   "estimatedDateOfCompletion":"22-06-2020",
   "allotedEmployee":"raj",
   "totalAmountInINR":"30000",
   "advanceAmountInINR":"10000",
   "status":"not_started",
   "isPaymentCompleted":"yes"
}

### editor view order
GET http://localhost:8080/api/editor/view-single-order/5ee74ff0dd948038ecf3cd2c
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

### editor updating order
PATCH http://localhost:8080/api/editor/update-order/5ee74ff0dd948038ecf3cd2c
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

{  
   "status": "completed",
   "isPaymentCompleted":"yes"
}

### editor filtering orders
GET http://localhost:8080/api/editor/filter-orders?status=not_started
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o


### editor payment done and order  completed 
GET http://localhost:8080/api/editor/payment-done-and-completed-orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

### editor all customers
GET http://localhost:8080/api/editor/all-customers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o


### editor searching customers by studio name
GET http://localhost:8080/api/editor/search/customers-by-office-name?officeName=customer1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o


### editor customer orders
GET http://localhost:8080/api/editor/customer-orders/5ee74eac6f17882db429c490
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o

### editor searching orders
GET http://localhost:8080/api/editor/search/orders-by-title?titleOfOrder=anniversary
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3MmEzNmM0MjdiNjM1YzAwY2VhNGEiLCJpYXQiOjE1OTIyMTcxNjgsImV4cCI6MTU5MjMwMzU2OH0.lDdEZbr6JfaSQSaRYidkR1DjdOneUU_iJWAaWVerk7o





















############################   customer routes   #######################

### customer login
POST http://localhost:8080/api/customer/login
Content-Type: application/json

{  
   "email": "customer1@gmail.com",
   "password": "123456"
}


###  customer logout
DELETE http://localhost:8080/api/customer/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

### customer forgot password
PATCH  http://localhost:8080/api/customer/forgot-password
Content-Type: application/json

{  
   "email": "customer1@gmail.com",
   "mobile": "9123456789"
}


### customer change password
PATCH  http://localhost:8080/api/customer/change-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

{  
   "currentPassword": "7998117",
   "newPassword": "123456"
}

### customer viewing all editors
GET http://localhost:8080/api/customer/all-editors
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

### customer all viewing orders
GET http://localhost:8080/api/customer/orders-in-specific-editor/5ee72a36c427b635c00cea4a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

### customer view single order
GET http://localhost:8080/api/customer/view-single-order/5ee74ff0dd948038ecf3cd2c
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

### customer search orders by title
GET http://localhost:8080/api/customer/search/orders-by-title?titleOfOrder=anniversary
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWU3NGVhYzZmMTc4ODJkYjQyOWM0OTAiLCJpYXQiOjE1OTIyMjMzODAsImV4cCI6MTU5MjMwOTc4MH0.S75NfJFGetGfU2ogjVK_S4rFXoaggKVtDoSP_153OvQ

